### ISSUE TITLE
Not loading feed?

### ISSUE THREAD

**Issue by ghost** [jasoncheng/mawa-android#139]
Getting this error message twice upon refresh:

temporary unable to use
(java.lang.IllegalState Exception: Expected
BEGIN_ARRAY but was BOOLEAN at line 1
column 3380 path $[0].attachments)

**Comment by jasoncheng** [comment]
Do you know what version your Friendica is? This should not happen for Friendica API would not response Boolean for attachments , maybe you can try on meld.de , it's running last RC.

**Comment by jasoncheng** [comment]
Or please let me know your Friendica host name, I would check when I back to home

**Comment by ghost** [comment]
I downloaded the latest version from the Play Store. However, the server I use is spraci.info.

**Comment by jasoncheng** [comment]
oh, it's 2018/05 release, could you suggest the administrator of spracu.info to upgrade to latest? DiCa start since 2018/11, the API could be not support legacy API

http://spraci.info/friendica

**Comment by ghost** [comment]
Okay, I'll try that. Thanks!

**Comment by jasoncheng** [comment]
You're welcome, thanks for using DiCa 😁

**Comment by jasoncheng** [comment]
Upgrade to 2018/09 RC, would be great too
