### ISSUE TITLE
searching

### ISSUE THREAD

**Issue by Rik44444** [jasoncheng/mawa-android#143]
Hi,
1) am i correct to say that there is currently no button to start searches in the app (e.g. for hashtags, e.g. #photography ) ? I noticed searching is possible, because when i press on a hashtag posted by someone else, the app takes me to a search window, where i can then search also for other hashtags. 
2) searches like these have never given me any results, it just keeps loading. Do others have this too?
Rik

**Comment by jasoncheng** [comment]
It's a long story, take a look at https://github.com/jasoncheng/dica/issues/99 first.

In short, hashtag search, yes, but still on develop branch(meld.de support)

text search, performance issue, dica not enable yet, it's depends next Friendica API
