### ISSUE TITLE
Text input field is hidden when keyboard pops up

### ISSUE THREAD

**Issue by hoergen** [jasoncheng/mawa-android#148]
Starting a new post, the text input field is hidden, when the (AnySoftkeyboard pops up). So I can't see what I'm writing.

system
Phone: OnePlus3t
OS: LineageOS: 13.x
Android: 7.1.2

![00_temp](https://user-images.githubusercontent.com/24474762/51913413-b6e5d580-23d6-11e9-8a4a-93d7db5e8e61.jpg)

**Comment by jasoncheng** [comment]
https://download.lineageos.org/oneplus3

**Comment by jasoncheng** [comment]
@hoergen any update? Is new OnePlus OS still have this issue?

**Comment by ghost** [comment]
I think thats LineageOS

**Comment by hoergen** [comment]
Update planned next sunday. ;)

**Comment by jasoncheng** [comment]
@hoergen Roger that

**Comment by hoergen** [comment]
Needed to postpone the update, but i will give a feedback as soon I could do the update.

**Comment by hoergen** [comment]
Finally i managed to upgrade my phones ROM from LineageOS 13 to LineageOS 16 and the problem doesn't exist anymore. But thank you for your patients.
