### ISSUE TITLE
Play Store says: Device not compatible!?

### ISSUE THREAD

**Issue by JostAusSoest** [jasoncheng/mawa-android#149]
Supposedly the app is not compatible with my device.

Hardware: OnePlus One (bacon/A0001)
Software: LineageOS 15.1 (Android 8.1)
Rooted: Yes

**Comment by JostAusSoest** [comment]
BTW: Using the manually installed APK (v0.2.2-19011403) throws no error.

**Comment by jasoncheng** [comment]
@JostAusSoest Theoretically, DiCa support all device base on Android 5.0+, 
maybe you can open a issue on onePlus or [try this](https://forums.oneplus.com/threads/compatibility-issues-with-apps-on-the-play-store.678013/)

**Comment by jasoncheng** [comment]
@JostAusSoest Maybe download from [APK branch](https://github.com/jasoncheng/dica/tree/apk/apk) is a good start, BTW, thanks for using DiCa :)
